"""Add provider_id column to services

Revision ID: 7570360dbd5a
Revises: 0ba8f7ec4d5b
Create Date: 2023-10-20 19:12:34.049787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7570360dbd5a'
down_revision = '0ba8f7ec4d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('services', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'users', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'provider_id')
    op.drop_table('service_images')
    # ### end Alembic commands ###